[package]
name = "bootstrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.11", features = ["json", "blocking"] }
tokio = { version = "1", features = ["full"] }
walkdir = "2"
sha2 = "0.10"
sevenz-rust2 = "0.19"
anyhow = "1"
shell-escape = "0.1"
nix = { version = "0.30.1", optional = true }
windows = { version = "0.62.2", features = ["Win32_System_Threading", "Win32_UI_Shell", "Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Foundation"] }


[dev-dependencies]
assert_cmd = "2"
predicates = "3"
tempfile = "3"

